/** MCP ListTools definitions — keep in sync with schemas.ts */

export const MCP_TOOLS = [
  {
    name: "process_recommend",
    description:
      "Full laser welding recommendation from simple inputs: process parameters, equipment, DOE, BOM, risks, validation, and acceptance.",
    inputSchema: {
      type: "object" as const,
      properties: {
        material: { type: "string", description: "e.g. copper, stainless-304, 铜" },
        thicknessMm: { type: "number" },
        weldingMethod: { type: "string", description: "e.g. 叠焊, 拼焊, 角焊, lap, butt, fillet" },
        application: { type: "string" },
        lightTransmittance: { type: "number", description: "0-1, overrides catalog for plastics" },
        motionPlatform: { type: "string", enum: ["gantry", "single-axis", "galvo-scanner"] },
        laserHead: { type: "string", enum: ["galvo", "fixed-focus", "single-axis-rotation"] },
        preferredLaserType: {
          type: "string",
          enum: ["fiber-1064", "fiber-2um", "fiber-green", "diode-blue", "diode-semiconductor"],
        },
        fieldbusProtocol: { type: "string", enum: ["opc-ua", "profinet", "ethercat"] },
        includeVision: { type: "boolean" },
        seamLengthMm: { type: "number" },
        targetSpeedMmPerS: { type: "number" },
        gapMm: { type: "number" },
        wireFill: { type: "boolean" },
        wireDiameterMm: { type: "number" },
        targetPenetrationDepthMm: { type: "number" },
        baseMaterialB: { type: "string" },
        thicknessBMm: { type: "number" },
        coating: { type: "string" },
        surfaceCondition: { type: "string" },
        applicationScenario: {
          type: "string",
          enum: [
            "metal-fusion",
            "laser-brazing",
            "push-pull-brazing",
            "polymer-transmission",
            "battery-tab",
            "busbar",
            "seal-welding",
            "custom",
          ],
        },
        deliveryScope: {
          type: "string",
          enum: ["process-package", "equipment-package", "presales-solution"],
        },
        qualityTargets: {
          type: "array",
          items: {
            type: "string",
            enum: ["strength", "sealing", "conductivity", "appearance", "low-spatter", "low-heat-input"],
          },
        },
        targetTaktSec: { type: "number" },
        partsPerHour: { type: "number" },
        stationCount: { type: "number" },
        preferredBrands: { type: "array", items: { type: "string" } },
        forbiddenBrands: { type: "array", items: { type: "string" } },
        budgetLevel: {
          type: "string",
          enum: ["low", "mid", "high"],
          description: "Coarse complexity constraint only; never commercial values.",
        },
        wireFeedMode: { type: "string", enum: ["push-pull", "push", "pull", "manual-assist"] },
        wireFeedOrientation: {
          type: "string",
          enum: ["front", "rear", "side", "coaxial", "near-coaxial"],
        },
        brazingWireFamily: {
          type: "string",
          enum: ["CuSi", "AlSi", "Ni-based", "Cu-based", "stainless-filler", "custom"],
        },
      },
      required: ["material", "thicknessMm", "weldingMethod"],
    },
  },
  {
    name: "material_assess",
    description:
      "Stage 1: Process window with processParams (power curve, defocus sign, penetration), weldMode, lightTransmittance for plastics.",
    inputSchema: {
      type: "object" as const,
      properties: {
        material: { type: "string", description: "e.g. copper, pa66, 紫铜, PC" },
        thicknessMm: { type: "number" },
        jointType: { type: "string" },
        targetSpeedMmPerS: { type: "number" },
        gapMm: { type: "number" },
        wireFill: { type: "boolean" },
        wireDiameterMm: { type: "number" },
        targetPenetrationDepthMm: { type: "number" },
        lightTransmittance: { type: "number", description: "0–1, overrides catalog for plastics" },
        baseMaterialB: { type: "string" },
        thicknessBMm: { type: "number" },
        coating: { type: "string" },
        surfaceCondition: { type: "string" },
        applicationScenario: {
          type: "string",
          enum: [
            "metal-fusion",
            "laser-brazing",
            "push-pull-brazing",
            "polymer-transmission",
            "battery-tab",
            "busbar",
            "seal-welding",
            "custom",
          ],
        },
        qualityTargets: {
          type: "array",
          items: {
            type: "string",
            enum: ["strength", "sealing", "conductivity", "appearance", "low-spatter", "low-heat-input"],
          },
        },
        brazingWireFamily: {
          type: "string",
          enum: ["CuSi", "AlSi", "Ni-based", "Cu-based", "stainless-filler", "custom"],
        },
      },
      required: ["material", "thicknessMm"],
    },
  },
  {
    name: "hardware_recommend",
    description:
      "Stage 2: Laser brands, laserTypes, motionPlatform, laserHead, bomSummary, lineLayout; brazing/turnkey.",
    inputSchema: {
      type: "object" as const,
      properties: {
        material: { type: "string" },
        thicknessMm: { type: "number" },
        application: { type: "string" },
        motionPlatform: { type: "string", enum: ["gantry", "single-axis", "galvo-scanner"] },
        laserHead: { type: "string", enum: ["galvo", "fixed-focus", "single-axis-rotation"] },
        preferredLaserType: {
          type: "string",
          enum: ["fiber-1064", "fiber-2um", "fiber-green", "diode-blue", "diode-semiconductor"],
        },
        lightTransmittance: { type: "number" },
        applicationScenario: {
          type: "string",
          enum: [
            "metal-fusion",
            "laser-brazing",
            "push-pull-brazing",
            "polymer-transmission",
            "battery-tab",
            "busbar",
            "seal-welding",
            "custom",
          ],
        },
        deliveryScope: {
          type: "string",
          enum: ["process-package", "equipment-package", "presales-solution"],
        },
        automationLevel: {
          type: "string",
          enum: ["manual", "semi-auto", "robot", "gantry-line", "galvo-line", "turnkey-line"],
        },
        targetTaktSec: { type: "number" },
        annualVolume: { type: "number" },
        partsPerHour: { type: "number" },
        stationCount: { type: "number" },
        preferredBrands: { type: "array", items: { type: "string" } },
        forbiddenBrands: { type: "array", items: { type: "string" } },
        budgetLevel: {
          type: "string",
          enum: ["low", "mid", "high"],
          description: "Coarse complexity constraint only; never commercial values.",
        },
        wireFeedMode: { type: "string", enum: ["push-pull", "push", "pull", "manual-assist"] },
        wireFeedOrientation: {
          type: "string",
          enum: ["front", "rear", "side", "coaxial", "near-coaxial"],
        },
        wireFeedAngleDeg: { type: "number" },
        wireNozzleOffsetMm: { type: "number" },
        wireSpeedMmPerS: { type: "number" },
        headCoolingRequired: { type: "boolean" },
        seamTrackingRequired: { type: "boolean" },
        preheatRequired: { type: "boolean" },
        collisionEnvelopeNotes: { type: "string" },
        brazingWireFamily: {
          type: "string",
          enum: ["CuSi", "AlSi", "Ni-based", "Cu-based", "stainless-filler", "custom"],
        },
      },
      required: ["material", "thicknessMm"],
    },
  },
  {
    name: "doe_matrix",
    description: "Stage 3: Power-speed DOE; optional defocusMin/Max, gapMin/Max, includeGapAxis.",
    inputSchema: {
      type: "object" as const,
      properties: {
        powerMin: { type: "number" },
        powerMax: { type: "number" },
        speedMin: { type: "number" },
        speedMax: { type: "number" },
        gridSize: { type: "number" },
        defocusMin: { type: "number" },
        defocusMax: { type: "number" },
        gapMin: { type: "number" },
        gapMax: { type: "number" },
        includeGapAxis: { type: "boolean" },
        wireSpeedMin: { type: "number" },
        wireSpeedMax: { type: "number" },
        wireFeedAngleMin: { type: "number" },
        wireFeedAngleMax: { type: "number" },
        preheatPowerMin: { type: "number" },
        preheatPowerMax: { type: "number" },
        shieldGasMin: { type: "number" },
        shieldGasMax: { type: "number" },
        clampForceMin: { type: "number" },
        clampForceMax: { type: "number" },
      },
      required: ["powerMin", "powerMax", "speedMin", "speedMax"],
    },
  },
  {
    name: "defect_diagnose",
    description: "Stage 3: Defect diagnosis (EN/ZH symptoms).",
    inputSchema: {
      type: "object" as const,
      properties: {
        symptom: { type: "string" },
        material: { type: "string" },
        thicknessMm: { type: "number" },
      },
      required: ["symptom", "material", "thicknessMm"],
    },
  },
  {
    name: "trajectory_generate",
    description: "Stage 4: G-code; galvo-scanner adds OEM export note.",
    inputSchema: {
      type: "object" as const,
      properties: {
        pathType: { type: "string", enum: ["line", "circle", "rectangle"] },
        lengthMm: { type: "number" },
        radiusMm: { type: "number" },
        widthMm: { type: "number" },
        heightMm: { type: "number" },
        speedMmPerS: { type: "number" },
        powerW: { type: "number" },
        dialect: { type: "string", enum: ["gcode", "fanuc"] },
        motionPlatform: { type: "string", enum: ["gantry", "single-axis", "galvo-scanner"] },
      },
      required: ["pathType", "speedMmPerS", "powerW"],
    },
  },
  {
    name: "fieldbus_map",
    description: "Stage 4: OPC UA, PROFINET, or EtherCAT.",
    inputSchema: {
      type: "object" as const,
      properties: {
        protocol: { type: "string", enum: ["opc-ua", "profinet", "ethercat"] },
      },
      required: ["protocol"],
    },
  },
  {
    name: "solution_bom",
    description:
      "Stage 4: Turnkey solution BOM — line items, quantities, line layout, turnkey vendors.",
    inputSchema: {
      type: "object" as const,
      properties: {
        material: { type: "string" },
        thicknessMm: { type: "number" },
        application: { type: "string" },
        motionPlatform: { type: "string", enum: ["gantry", "single-axis", "galvo-scanner"] },
        laserHead: { type: "string", enum: ["galvo", "fixed-focus", "single-axis-rotation"] },
        preferredLaserType: {
          type: "string",
          enum: ["fiber-1064", "fiber-2um", "fiber-green", "diode-blue", "diode-semiconductor"],
        },
        lightTransmittance: { type: "number" },
        fieldbusProtocol: { type: "string", enum: ["opc-ua", "profinet", "ethercat"] },
        includeVision: { type: "boolean" },
        wireFill: { type: "boolean" },
        gapMm: { type: "number" },
        applicationScenario: {
          type: "string",
          enum: [
            "metal-fusion",
            "laser-brazing",
            "push-pull-brazing",
            "polymer-transmission",
            "battery-tab",
            "busbar",
            "seal-welding",
            "custom",
          ],
        },
        deliveryScope: {
          type: "string",
          enum: ["process-package", "equipment-package", "presales-solution"],
        },
        baseMaterialB: { type: "string" },
        thicknessBMm: { type: "number" },
        jointType: { type: "string" },
        seamType: { type: "string" },
        seamLengthMm: { type: "number" },
        qualityTargets: {
          type: "array",
          items: {
            type: "string",
            enum: ["strength", "sealing", "conductivity", "appearance", "low-spatter", "low-heat-input"],
          },
        },
        targetTaktSec: { type: "number" },
        preferredBrands: { type: "array", items: { type: "string" } },
        forbiddenBrands: { type: "array", items: { type: "string" } },
        budgetLevel: {
          type: "string",
          enum: ["low", "mid", "high"],
          description: "Coarse complexity constraint only; never commercial values.",
        },
        wireFeedMode: { type: "string", enum: ["push-pull", "push", "pull", "manual-assist"] },
        wireFeedOrientation: {
          type: "string",
          enum: ["front", "rear", "side", "coaxial", "near-coaxial"],
        },
        wireFeedAngleDeg: { type: "number" },
        wireNozzleOffsetMm: { type: "number" },
        wireSpeedMmPerS: { type: "number" },
        headCoolingRequired: { type: "boolean" },
        seamTrackingRequired: { type: "boolean" },
        preheatRequired: { type: "boolean" },
        collisionEnvelopeNotes: { type: "string" },
        brazingWireFamily: {
          type: "string",
          enum: ["CuSi", "AlSi", "Ni-based", "Cu-based", "stainless-filler", "custom"],
        },
        safetyLevel: { type: "string" },
        plantUtilities: { type: "array", items: { type: "string" } },
        fixtureComplexity: { type: "string", enum: ["low", "medium", "high"] },
        mesIntegrationRequired: { type: "boolean" },
        plcPreference: { type: "string" },
      },
      required: ["material", "thicknessMm"],
    },
  },
] as const;
